 
[*]  ; Глобальные дефолты для всех моделей
ctx-size     = 65536        ; размер контекста (пример из автора)
batch-size   = 4096         ; логический максимум batch (n_batch)
ubatch-size  = 4096         ; физический максимум (n_ubatch) — см. бенч
ngl          = 99           ; все слои на GPU
no-mmap      = 1
mlock        = 1
temp         = 0.7
n-predict    = 32000
jinja        = 1
metrics      = 1
cache-reuse  = 256          ; reuse KV для агентных промптов
threads      = 4            ; по твоему бенчу хороший баланс PP/TG
ctk          = turbo4       ; TurboQuant KV для K
ctv          = turbo2       ; TurboQuant KV для V

[qwen36-reap]
model = /var/lib/llama-server/models/Qwen3.6-28B-REAP20-A3B-Q4_K_M.gguf
alias            = qwen36-reap
n-cpu-moe        = 17        ; как в бенче, безопасно по VRAM
temp             = 0.7
top-p            = 0.95
top-k            = 20
min-p            = 0.0
presence-penalty = 0.0
repeat-penalty   = 1.0
chat-template-file = /etc/llama-server/qwen-aware-mimo-tool-template.jinja


[qwen36-reap-long-context]
model = /var/lib/llama-server/models/Qwen3.6-28B-REAP20-A3B-Q4_K_M.gguf
alias            = qwen36-reap-long-context
ctx-size     = 131072        
n-cpu-moe        = 17        ; как в бенче, безопасно по VRAM
temp             = 0.7
top-p            = 0.95
top-k            = 20
min-p            = 0.0
presence-penalty = 0.0
repeat-penalty   = 1.0
chat-template-file = /etc/llama-server/qwen-aware-mimo-tool-template.jinja
;ctk          = q8_0       
;ctv          = q8_0       

; сюда позже добавишь GLM, когда прогоняешь бенч под неё
; [glm47-flash-reap]
; model  = /home/you/models/GLM-4.7-Flash-REAP-23B-A3B-IQ4_XS.gguf
; alias  = glm-4.7-flash-reap
; temp   = 0.7
; top-p  = 1.0
; top-k  = 40
